# Generated by Django 2.2.1 on 2019-06-26 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='sex',
        ),
    ]
