# Generated by Django 2.2.1 on 2019-06-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20190628_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='img',
            field=models.ImageField(default='13912B24602642CE96E9A5BDFD7605AC_zuHkkXY.png', upload_to='media/images'),
        ),
    ]
