# Generated by Django 2.2.1 on 2019-06-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_uploadimage_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='img',
            field=models.ImageField(default='13912B24602642CE96E9A5BDFD7605AC_zuHkkXY.png', upload_to='media/'),
        ),
    ]
