# Generated by Django 2.2.1 on 2019-06-28 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20190628_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='img',
        ),
    ]
