# Generated by Django 2.2.1 on 2019-06-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_remove_uploadimage_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='url',
            field=models.CharField(default='13912B24602642CE96E9A5BDFD7605AC_zuHkkXY.png', max_length=100),
        ),
    ]
